// This file was autogenerated by libs/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/acorn/base/behavior.js', ['acorn.base.Behavior'], []);
goog.addDependency('../../../../src/acorn/base/component.js', ['acorn.base.Component'], []);
goog.addDependency('../../../../src/acorn/base/entity.js', ['acorn.base.Entity'], ['acorn.base.Behavior', 'acorn.base.Component', 'goog.array']);
